applications:
- api_domain: api.github.io
  application_name: app name
  authentication_mode: non-authenticated
  exclude_paths: []
  target_url: https://stklauz.github.io
  type: web
deployment:
  environments:
  - ze miguel
plan_items:
  item-web-app-scanner:
    deployment:
      configuration:
      - app name
      tags:
      - ze miguel
      trigger: deployment
